#
# UFRGS - Compiladores B - Marcelo Johann - 2009/2 - Etapa 1
#
# Makefile for two compiler calls
# The code generated by lex and main.c are separately compiled
# You must include lex.yy.h in your main as well as the definition of
# other interfaces like getLineNumber, initMe, running...
# Use make clean to remove old files before remaking everything
#

etapa2: y.tab.o lex.yy.o main.o symbol_table.o
	gcc -o etapa2 y.tab.o lex.yy.o main.o symbol_table.o

lex.yy.o: lex.yy.c
	gcc -c lex.yy.c
y.tab.o: y.tab.c
	gcc -c y.tab.c
main.o: main.c
	gcc -c main.c
symbol_table.o: symbol_table.c
	gcc -c symbol_table.c
y.tab.c: parser.y
	yacc -v -d parser.y
lex.yy.c: scanner.l
	flex --header-file=lex.yy.h scanner.l
clean:
	rm *.o lex.yy.c y.tab.c y.tab.h y.output etapa2
