#
# UFRGS - Compiladores B - Marcelo Johann - 2009/2 - Etapa 5
#
# Makefile for two compiler calls
# The code generated by lex and main.c are separately compiled
# You must include lex.yy.h in your main as well as the definition of
# other interfaces like getLineNumber, initMe, running...
# Use make clean to remove old files before remaking everything
#

etapa6: y.tab.o lex.yy.o main.o symbol_table.o ast.o semantic.o tac.o assembler.o
	gcc -o etapa6 y.tab.o lex.yy.o main.o symbol_table.o ast.o semantic.o tac.o assembler.o

main.o: main.c
	gcc -c main.c
symbol_table.o: symbol_table.c
	gcc -c symbol_table.c
semantic.o: semantic.c
	gcc -c semantic.c
ast.o: ast.c
	gcc -c ast.c
tac.o: tac.c
	gcc -c tac.c
assembler.o: assembler.c
	gcc -c assembler.c
lex.yy.o: lex.yy.c
	gcc -c lex.yy.c
y.tab.o: y.tab.c
	gcc -c y.tab.c
y.tab.c: parser.y
	yacc -v -d parser.y
lex.yy.c: scanner.l
	flex --header-file=lex.yy.h scanner.l
clean:
	rm *.o lex.yy.c lex.yy.h y.tab.c y.tab.h y.output etapa6
